echo "<!-- Do not edit this file (Sidebar.html) directly -->" > Sidebar.html
cat Sidebarstart.html >> Sidebar.html

echo "<script>" >> Sidebar.html
cat ../blockly_compressed.js >> Sidebar.html
echo "</script><script>" >> Sidebar.html
cat ../blocks_compressed.js >> Sidebar.html
echo "</script><script>" >> Sidebar.html
cat ../blocks/sheetsblocks.js >> Sidebar.html
echo "</script>" >> Sidebar.html
echo "<script>" >> Sidebar.html
cat ../msg/js/en.js >> Sidebar.html
echo "</script>" >> Sidebar.html

cat Sidebarbodyend.html >> Sidebar.html
