echo "<!-- Do not edit this file (Sidebar.html) directly -->" > Sidebar.html
cat Sidebarstart.html >> Sidebar.html

echo "<script>" >> Sidebar.html
cat ../blockly_compressed.js >> Sidebar.html
echo "</script><script>" >> Sidebar.html
cat ../blocks_compressed.js >> Sidebar.html
echo "</script><script>" >> Sidebar.html
cat ../blocks/sheetsblocks.js >> Sidebar.html
echo "</script>" >> Sidebar.html
echo "<script>" >> Sidebar.html
cat ../msg/js/en.js >> Sidebar.html
echo "</script>" >> Sidebar.html

# Generate the formulas client side
echo "<script>" >> Sidebar.html
cat ../generators/sheets.js >> Sidebar.html
echo "</script>" >> Sidebar.html

for value in sheetsblocks.js colour.js lists.js logic.js loops.js math.js procedures.js text.js variables.js
do
echo "<script>" >> Sidebar.html
cat "../generators/sheets/$value" >> Sidebar.html
echo "</script>" >> Sidebar.html
done

cat SidebarHeadEnd.html >> Sidebar.html
echo "<body>" >> Sidebar.html
cat toolbox.xml >> Sidebar.html
cat startBlocks.xml >> Sidebar.html
cat Sidebarbodyend.html >> Sidebar.html
